/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "main.h"

int main(void)
{
	RCC_AHB1ENR_t volatile * const pRccAhb1 = (RCC_AHB1ENR_t*) 0x40023830;
	GPIOx_MODE_t volatile * const pGpioAmode = (GPIOx_MODE_t*) 0x40020000;
	GPIOx_ODR_t volatile * const pGpioAodr = (GPIOx_ODR_t*) 0x40020014;
	//pGpioAmode = (GPIOx_MODE_t*) 0x40020000;

	pRccAhb1->gpioa_en = 1;

	pGpioAmode->mode5 = 1;

	while (1) {
		for (uint64_t volatile i = 0; i < 500000; ++i);
		if (pGpioAodr->odr5)
			pGpioAodr->odr5 = 0;
		else
			pGpioAodr->odr5 = 1;
	}

	for(;;);
}
